name: test-action

on:
  - push
  - workflow_dispatch

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
        with:
          path: .

      - name: Check unit tests
        id: unit-test
        uses: bfv/openedge-flatversion@main
        with:
          version: '12.8.2'
      
      - name: Check result, flat version
        run: |
          echo "flat-version is ${{ steps.unit-test.outputs.flat-version }}"
          if [[ "${{ steps.unit-test.outputs.flat-version }}" != "128" ]]; then
            echo "flat-version is not 128"
            exit 1
          fi

      - name: Check result, release version
        run: |
          echo "release-version is ${{ steps.unit-test.outputs.release-version }}"
          if [[ "${{ steps.unit-test.outputs.release-version }}" != "12.8" ]]; then
            echo "release-version is not 12.8"
            exit 1
          fi
      
        