name: test-action

on:
  - push
  - workflow_dispatch

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
        with:
          path: .

      - name: Check unit tests
        id: unit-test
        uses: bfv/openedge-flatversion@main
        with:
          version: '12.8.2'
      
      - name: Check result
        run: echo "Flat version is ${{ steps.unit-test.outputs.flat-version }}"
        